server:
  port: 8080
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        password: nacos
        username: nacos
        namespace: public
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.zhang.orders.rule.CustomRule # com.alibaba.cloud.nacos.ribbon.NacosRule
