server:
  port: 8081
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        password: nacos
        username: nacos
        namespace: public