server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    # gateway 配置
    gateway:
      # 路由规则
      routes:
        - id: order_route # 路由唯一标识
          uri: lb://order-service  # 需要转发的地址  http://localhost:8080 ,配置nacos后只需要配置服务名即可
          # 断言规则，用于路由规则的匹配
          predicates:
            - Path=/flow/** # http://localhost:8085/order-server/gateway 路由到
                                    # http://localhost:8080/order-server/gateway
#            - After=2022-01-20T17:42:47.789-07:00[Asia/Shanghai]
#            - Header=X-Request-Id, \d+
#            - Method=GET
#            - CheckAuth=zhang
          filters:
            - AddRequestHeader=X-Request-red, blue
#            - StripPrefix=1 # 在转发前去掉第一层路径 http://localhost:8080/gateway
        # - id: stock_route
      globalcors:
        cors-configurations:
          '[/**]': # 允许跨域访问的资源
            allowedOrigins: "https://docs.spring.io" # 跨域允许的来源,可以配置为 * ，代表所有的都允许，默认就是 *
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
    # 配置nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8888
  main:
    web-application-type: reactive


